# Practice questions 22MIA1064 (Yasir Ahmad)

In [6]:
import numpy as np

## Question 1: Solve given equations  
> 4x + 3y + 2z = 25  
> -2x + 2y +3z = -10  
> 3x - 5y + 2z = -4  

In [17]:
A = np.array([[4,3,2],[-2,2,3],[3,-5,2]])
B = np.array([25,-10,-4])
X = np.linalg.solve(A,B)
print(X)

[ 5.  3. -2.]


## Question 2: Implement a function to calculate rank,determinant and inverse of sq matrix

In [12]:
def calc(A):
    rnk = np.linalg.matrix_rank(A)
    det = np.linalg.det(A)
    inv = np.linalg.inv(A)
    
    return rnk,det,inv

In [7]:
A = np.array([[3,4,2],[6,2,1],[9,7,8]])

In [8]:
A

array([[3, 4, 2],
       [6, 2, 1],
       [9, 7, 8]])

In [13]:
calc(A)

(3,
 -80.99999999999996,
 array([[-1.11111111e-01,  2.22222222e-01,  3.08395285e-18],
        [ 4.81481481e-01, -7.40740741e-02, -1.11111111e-01],
        [-2.96296296e-01, -1.85185185e-01,  2.22222222e-01]]))