In [3]:
import numpy as np

In [6]:
#Creating a rank 1 Array
arr = np.array([1,2,3])
print("Array: ",arr)

Array:  [1 2 3]


In [8]:
#Creating array of rank 2
arr = np.array([[1,2,3],[4,5,6]])
print("Array :\n",arr)

Array :
 [[1 2 3]
 [4 5 6]]


In [55]:
#type of array
print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [56]:
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

No. of dimensions:  1


In [57]:
# Printing shape of array
print("Shape of array: ", arr.shape)
 # Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 # Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Shape of array:  (5,)
Size of array:  5
Array stores elements of type:  int32


In [9]:
#arange
f = np.arange(0,30,5)
print("A sequential arrays with steps 5:\n",f)

A sequential arrays with steps 5:
 [ 0  5 10 15 20 25]


In [10]:
#linspace
g = np.linspace(0,5,10)
print("A sequential array :\n",g)

A sequential array :
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [73]:
#Reshaping
arr = np.array([[1,2,3,4],[5,6,7,8],[4,3,2,1]])
print("Array shape:",arr.shape)
newarr = arr.reshape(2,2,3)
print("Original Array:\n",arr)
print("Array:\n",newarr)
print("Array shape:",newarr.shape)

Array shape: (3, 4)
Original Array:
 [[1 2 3 4]
 [5 6 7 8]
 [4 3 2 1]]
Array:
 [[[1 2 3]
  [4 5 6]]

 [[7 8 4]
  [3 2 1]]]
Array shape: (2, 2, 3)


In [61]:
#indexing
#arr[i,j,k]
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [64]:
#slicing
#arr[start:stop:steps]
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[2 4]
[[2 3 4]
 [7 8 9]]


In [60]:
#data types
#arr.dtype
#astype() - to convert the datatype
""" 
i - integer
f - float
c - complex
s - string
"""
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list, type float:\n", a)
# Creating array from tuple
b = a.astype("i")
print ("Array type int:\n", b)

Array created using passed list, type float:
 [[1. 2. 4.]
 [5. 8. 7.]]
Array type int:
 [[1 2 4]
 [5 8 7]]


In [33]:
#view
arr = np.array([1,2,3,4])
x = arr.view()
arr[0] = 42
print("Original:",arr)
print("View:",x)

Original: [42  2  3  4]
View: [42  2  3  4]


In [34]:
#copy
x = arr.copy()
arr[0] = 1
print("Original:",arr)
print("View:",x)

Original: [1 2 3 4]
View: [42  2  3  4]


In [75]:
#iteration
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
 print(x)


[1 2 3]
[4 5 6]


In [76]:
#concatenate
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr,"axis 1")
arr = np.concatenate((arr1, arr2), axis=0)
print(arr,"axis 0")

[[1 2 5 6]
 [3 4 7 8]] axis 1
[[1 2]
 [3 4]
 [5 6]
 [7 8]] axis 0


In [77]:
#split
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [35]:
#Searching
#where
x = np.where(arr==4)
print(x)

(array([3], dtype=int32),)


In [36]:
#searchsorted
arr = np.array([9,8,3,6])
x = np.searchsorted(arr,7)
print(x)

4


In [39]:
#sort
print(arr)
print(np.sort(arr))

[9 8 3 6]
[3 6 8 9]


## Basic Array Operations


* ### Unary Operators



In [80]:
#basic array operations
arr = np.array([[2,3],[6,7]])
print("Array:",arr)
#increment
print("Increment:",arr+1)
#decrement
print("Decrement:",arr-1)
#agg function
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
# sum of array elements
print ("Sum of all array elements:",arr.sum())
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))
# cumulative sum along each column
print ("Cumulative sum along each column:\n",arr.cumsum(axis = 0))

Array: [[2 3]
 [6 7]]
Increment: [[3 4]
 [7 8]]
Decrement: [[1 2]
 [5 6]]
Largest element is: 7
Row-wise maximum elements: [3 7]
Sum of all array elements: 18
Cumulative sum along each row:
 [[ 2  5]
 [ 6 13]]
Cumulative sum along each column:
 [[ 2  3]
 [ 8 10]]


* ### Binary Operators

In [50]:
a = np.array([[2,3],[1,7]])
b = np.array([[5,6],[4,1]])
print("Original Arrays:\n","A:\n",a,"\nB:\n",b)
#add arrays
print("Array sum:\n",a+b)
#diff arrays
print("Arrays diff:\n",a-b)
#multiplication (element wise)
print("Arrays multiplication:\n",a*b)

Original Arrays:
 A:
 [[2 3]
 [1 7]] 
B:
 [[5 6]
 [4 1]]
Array sum:
 [[7 9]
 [5 8]]
Arrays diff:
 [[-3 -3]
 [-3  6]]
Arrays multiplication:
 [[10 18]
 [ 4  7]]


In [51]:
#Dot product
print("Array dot product:\n",a.dot(b))

Array dot product:
 [[22 15]
 [33 13]]


* ### Universal Functions


In [81]:
#Universal Functions
arr1 = np.array([1,2,5,4,6,2,3])
arr2 = np.array([3,4,2,1,4,1,2])

#divide
newarr = np.divide(arr1, arr2)
print(newarr)

#mod
print(np.mod(arr1,arr2))

#remainder
newarr = np.remainder(arr1, arr2)
print(newarr)

#absolute
arr = np.array([-1, -2, 1, 2, 3, -4])
newarr=np.absolute(arr)
print(newarr)

#trunc
arr = np.trunc([-3.14, 6.1111])
print(arr)

#exp
#pow
#divmod

#around
arr = np.around(3.1666, 2)
print(arr)

#fix
arr = np.fix([-3.14, 4.6667])
print(arr)

#floor
arr = np.floor([-3.14, 4.6667])
print(arr)

#ceil
arr = np.ceil([-3.14, 4.6667])
print(arr)

#gcd
num1=365
num2=14
x = np.gcd(num1, num2)
print(x)

#gcd.reduce
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

#log
print(np.log(arr))

#log10
print(np.log10(arr))

#log2
print(np.log2(arr))

[0.33333333 0.5        2.5        4.         1.5        2.
 1.5       ]
[1 2 1 0 2 0 1]
[1 2 1 0 2 0 1]
[1 2 1 2 3 4]
[-3.  6.]
3.17
[-3.  4.]
[-4.  4.]
[-3.  5.]
1
4
[2.99573227 2.07944154 3.4657359  3.58351894 2.77258872]
[1.30103    0.90308999 1.50514998 1.5563025  1.20411998]
[4.32192809 3.         5.         5.169925   4.        ]
