# Linear Algebra in Numpy  (22MIA1064 Y@sir Ahmad)
Linear algebra related operations in Python using Numpy
can help calculate rank,determinant


In [1]:
import numpy as np

* Import `np.linalg` module from numpy package

In [ ]:
import np.lin

In [2]:
#np.dot(a,b)
#np.vdot(a,b)
a = np.array([13,21,45])
b = np.array([3,6,5])


In [3]:
a.dot(b)

390

In [4]:
np.dot(a,b)

390

In [5]:
np.vdot(a,b)

390

In [7]:
a.shape

(3,)

In [8]:
a = np.array([[1,2],[2,3]])
b = np.array([[3,4],[5,6]])

In [9]:
a.dot(b)

array([[13, 16],
       [21, 26]])

In [10]:
np.dot(a,b)

array([[13, 16],
       [21, 26]])

In [11]:
np.vdot(a,b)

39

In [12]:
help(np.vdot)

Help on function vdot in module numpy:

vdot(...)
    vdot(a, b, /)
    
    Return the dot product of two vectors.
    
    The vdot(`a`, `b`) function handles complex numbers differently than
    dot(`a`, `b`).  If the first argument is complex the complex conjugate
    of the first argument is used for the calculation of the dot product.
    
    Note that `vdot` handles multidimensional arrays differently than `dot`:
    it does *not* perform a matrix product, but flattens input arguments
    to 1-D vectors first. Consequently, it should only be used for vectors.
    
    Parameters
    ----------
    a : array_like
        If `a` is complex the complex conjugate is taken before calculation
        of the dot product.
    b : array_like
        Second argument to the dot product.
    
    Returns
    -------
    output : ndarray
        Dot product of `a` and `b`.  Can be an int, float, or
        complex depending on the types of `a` and `b`.
    
    See Also
    --------
    dot

## Q1 solve linear eq 
solve given linear eq

> 4**x** + 3**y** = 20  
> -5**x** + 9**y** = 26   



> # Solution  
Represent in form Ax = B  
So, A = [4,3][-5,9]  
    B = [20][26]

In [24]:
A = np.array([[4,3],[-5,9]])
B = np.array([20,26])
Ai = np.linalg.inv(A) 

In [23]:
X = np.dot(Ai,B)

array([2., 4.])

### SOLVE  
Solving using `np.linalg.solve` function.  

In [28]:
X = np.linalg.solve(A,B)

In [30]:
X

array([2., 4.])

## Generate matrices  
* Identity Matrix
* Diagonal Matrix
* ones
* zeroes


## Rank, Trace and Determinant

* **Rank**  R space

In [31]:
np.linalg.matrix_rank(A)

2

* **Trace** Sum of diagonal elements

In [36]:
A.trace()

13

* **Determinant** Calculates determinant of the matrix

In [33]:
np.linalg.det(A)

50.99999999999997

* **Inverse** Calculate inverse of a matrix

In [39]:
np.linalg.inv(A) 

array([[ 0.17647059, -0.05882353],
       [ 0.09803922,  0.07843137]])

* **Power** Raise matrix to power n

In [38]:
np.linalg.matrix_power(A,3
                      )

array([[-191,  354],
       [-590,  399]])

# Eigen Value and Functions  

* `np.linalg.eig(A)` for eigen value,eigen vector of A of Rspace  


In [43]:
np.linalg.eig(A)

(array([6.5+2.95803989j, 6.5-2.95803989j]),
 array([[0.39528471-0.46770717j, 0.39528471+0.46770717j],
        [0.79056942+0.j        , 0.79056942-0.j        ]]))

* `np.linalg.eigh(A)` for eigen value,eigen vector for A of Zspace

In [44]:
A = np.array([[1,-2j],[2j,5+2j]])

In [45]:
np.linalg.eigh(A)

(array([0.17157288, 5.82842712]),
 array([[-0.92387953+0.j        , -0.38268343+0.j        ],
        [ 0.        +0.38268343j,  0.        -0.92387953j]]))

In [46]:
c,d = np.linalg.eigh(A)

In [47]:
print("Eigen value:",c)
print("Eigen vector:",d)

Eigen value: [0.17157288 5.82842712]
Eigen vector: [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


## Ravel Functions  

Flattens the higher dimensional arrays into 1-D arrays


In [56]:
A

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+2.j]])

In [53]:
np.ravel(A) #row-wise

array([ 1.+0.j, -0.-2.j,  0.+2.j,  5.+2.j])

In [54]:
np.ravel(A,order='F') #column-wise

array([ 1.+0.j,  0.+2.j, -0.-2.j,  5.+2.j])