# Linear Algebra in Scipy  (22MIA1064 Y@sir Ahmad)  

Scipy can be used to do linear algebra, but numpy needs to be imported first   


In [2]:
import numpy as np

In [3]:
import scipy

## Solve linear equations

In [4]:
a = np.array([[7,2],[4,5]])
b = np.array([8,10])

In [5]:
res = scipy.linalg.solve(a,b)

In [6]:
res

array([0.74074074, 1.40740741])

## Eigen Values and functions

In [7]:
scipy.linalg.eig(a)

(array([9.+0.j, 3.+0.j]),
 array([[ 0.70710678, -0.4472136 ],
        [ 0.70710678,  0.89442719]]))

## Singular Value Decomposition   
method for reducing matrix into its constituent parts to make specific subscequent matrix calculations simpler.

In [10]:
a,b,c = scipy.linalg.svd(np.matrix(res))

In [11]:
a,b,c

(array([[-1.]]),
 array([1.59043782]),
 array([[-0.46574643, -0.88491822],
        [-0.88491822,  0.46574643]]))